import { useState } from "react";
import { toast } from "sonner";
import { Download, Copy, Wand2, RotateCcw } from "lucide-react";

const GESTURES = [
  ["pinch", "👌 Pinch"], ["pinch_hold", "👌 Pinch-hold"], ["thumb_up", "👍 Thumb up"],
  ["thumb_down", "👎 Thumb down"], ["fist", "✊ Fist"], ["open_palm", "🖐 Open palm"],
  ["point", "☝ Point"], ["victory", "✌ Victory"], ["three", "✸ Three fingers"],
  ["four", "✥ Four fingers"], ["pinky", "☟ Pinky"], ["rock", "🤘 Rock"],
  ["call_me", "🤙 Call-me"], ["l_shape", "L-shape"], ["spiderman", "🕸 Spiderman"],
];
const ACTIONS = ["none", "click", "double_click", "drag", "scroll", "hotkey", "press", "type", "media", "launch", "screenshot", "window", "pause_toggle"];
const MEDIA = ["playpause", "next", "prev", "volup", "voldown", "mute"];
const WINDOW_OPS = ["switch", "minimize", "maximize", "close", "show_desktop"];
const CONTINUOUS = new Set(["pinch", "pinch_hold", "thumb_up", "thumb_down"]);

const DEFAULT_BINDINGS = {
  pinch: { action: "click", button: "left", hold: false },
  pinch_hold: { action: "drag", hold: false },
  thumb_up: { action: "scroll", amount: 1, hold: false },
  thumb_down: { action: "scroll", amount: -1, hold: false },
  open_palm: { action: "click", button: "right", hold: true },
  fist: { action: "screenshot", dir: "~/Pictures", hold: true },
  victory: { action: "window", op: "switch", hold: true },
  three: { action: "hotkey", keys: "ctrl+c", hold: true },
  four: { action: "media", key: "playpause", hold: true },
  pinky: { action: "media", key: "volup", hold: true },
  rock: { action: "media", key: "voldown", hold: true },
  call_me: { action: "launch", app: "notepad", hold: true },
  l_shape: { action: "hotkey", keys: "ctrl+v", hold: true },
  spiderman: { action: "pause_toggle", hold: true },
  point: { action: "none", hold: true },
};
const DEFAULT_SETTINGS = {
  camera: 0, edge_reach: 0.18, smoothing: 0.35, pinch_threshold: 0.055,
  hold_seconds: 1.0, cooldown_seconds: 1.5, scroll_speed: 1.0,
  mirror: true, move_cursor: true, start_paused: false, max_hands: 1,
};

const inputCls = "bg-[#0a0a0a] border border-zinc-800 text-white px-2 py-1.5 text-xs font-mono focus:outline-none focus:border-primary transition-colors w-full";

export function GestureConfigBuilder() {
  const [bindings, setBindings] = useState(() => JSON.parse(JSON.stringify(DEFAULT_BINDINGS)));
  const [settings, setSettings] = useState(() => ({ ...DEFAULT_SETTINGS }));

  const update = (g, patch) => setBindings((b) => ({ ...b, [g]: { ...b[g], ...patch } }));
  const setAction = (g, action) => {
    const base = { action, hold: bindings[g]?.hold ?? true };
    if (action === "click") base.button = bindings[g]?.button || "left";
    if (action === "scroll") base.amount = bindings[g]?.amount ?? 1;
    if (action === "hotkey") base.keys = bindings[g]?.keys || "ctrl+c";
    if (action === "press") base.key = bindings[g]?.key || "enter";
    if (action === "type") base.text = bindings[g]?.text || "";
    if (action === "media") base.key = MEDIA.includes(bindings[g]?.key) ? bindings[g].key : "playpause";
    if (action === "launch") base.app = bindings[g]?.app || "notepad";
    if (action === "screenshot") base.dir = bindings[g]?.dir || "~/Pictures";
    if (action === "window") base.op = bindings[g]?.op || "switch";
    setBindings((b) => ({ ...b, [g]: base }));
  };

  const buildConfig = () => ({
    _readme: "Generated by the InsafeLabs Config Builder. Edit freely; run the PC control script in the same folder and press 'r' to hot-reload.",
    settings, bindings,
  });
  const json = JSON.stringify(buildConfig(), null, 2);

  const downloadConfig = () => {
    const url = window.URL.createObjectURL(new Blob([json], { type: "application/json" }));
    const a = document.createElement("a");
    a.href = url; a.download = "insafelabs_gestures.json"; a.click();
    window.URL.revokeObjectURL(url);
    toast.success("Config downloaded — put it next to the script");
  };
  const copyJson = () => { navigator.clipboard.writeText(json); toast.success("Config JSON copied"); };
  const reset = () => { setBindings(JSON.parse(JSON.stringify(DEFAULT_BINDINGS))); setSettings({ ...DEFAULT_SETTINGS }); toast.message("Reset to defaults"); };

  return (
    <div className="border border-primary/30 bg-primary/[0.04] p-5 space-y-4" data-testid="gesture-config-builder">
      <div className="flex items-start gap-3 flex-wrap">
        <div>
          <p className="data-label text-primary mb-1 flex items-center gap-2"><Wand2 className="w-3.5 h-3.5" /> Visual Config Builder</p>
          <p className="text-sm text-zinc-300 max-w-2xl">Map each gesture to your own action, tune the settings, then download the <span className="font-mono text-primary">insafelabs_gestures.json</span> — no hand-editing needed. Drop it next to the PC control script.</p>
        </div>
        <div className="ml-auto flex gap-2">
          <button onClick={reset} data-testid="config-reset" className="border border-zinc-700 text-zinc-400 px-3 py-2 inline-flex items-center gap-1.5 hover:text-white transition-colors text-sm"><RotateCcw className="w-4 h-4" /> Reset</button>
          <button onClick={copyJson} data-testid="config-copy" className="border border-primary/40 text-primary px-3 py-2 inline-flex items-center gap-1.5 hover:bg-primary/10 transition-colors text-sm"><Copy className="w-4 h-4" /> Copy JSON</button>
          <button onClick={downloadConfig} data-testid="config-download" className="bg-primary text-black font-semibold px-4 py-2 inline-flex items-center gap-1.5 hover:bg-yellow-500 transition-colors text-sm"><Download className="w-4 h-4" /> Download Config</button>
        </div>
      </div>

      {/* settings */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 border border-border bg-[#0a0a0a] p-3">
        <label className="text-[11px] font-mono text-zinc-400">Camera index
          <input type="number" min="0" value={settings.camera} data-testid="config-camera"
            onChange={(e) => setSettings((s) => ({ ...s, camera: parseInt(e.target.value) || 0 }))} className={inputCls} /></label>
        <label className="text-[11px] font-mono text-zinc-400">Edge reach {Math.round(settings.edge_reach * 100)}%
          <input type="range" min="0" max="0.3" step="0.05" value={settings.edge_reach} data-testid="config-edge"
            onChange={(e) => setSettings((s) => ({ ...s, edge_reach: parseFloat(e.target.value) }))} className="w-full accent-primary" /></label>
        <label className="text-[11px] font-mono text-zinc-400">Smoothing {settings.smoothing.toFixed(2)}
          <input type="range" min="0.1" max="0.9" step="0.05" value={settings.smoothing} data-testid="config-smooth"
            onChange={(e) => setSettings((s) => ({ ...s, smoothing: parseFloat(e.target.value) }))} className="w-full accent-primary" /></label>
        <label className="text-[11px] font-mono text-zinc-400">Hold seconds {settings.hold_seconds.toFixed(1)}s
          <input type="range" min="0.4" max="2" step="0.1" value={settings.hold_seconds} data-testid="config-hold"
            onChange={(e) => setSettings((s) => ({ ...s, hold_seconds: parseFloat(e.target.value) }))} className="w-full accent-primary" /></label>
      </div>

      {/* bindings grid */}
      <div className="border border-border bg-[#0a0a0a] divide-y divide-border" data-testid="config-bindings">
        {GESTURES.map(([g, label]) => {
          const b = bindings[g] || { action: "none" };
          return (
            <div key={g} className="grid grid-cols-1 md:grid-cols-[150px_150px_1fr_70px] gap-2 items-center p-2.5" data-testid={`config-row-${g}`}>
              <span className="font-mono text-xs text-zinc-200">{label}</span>
              <select value={b.action} onChange={(e) => setAction(g, e.target.value)} data-testid={`config-action-${g}`} className={inputCls}>
                {ACTIONS.map((a) => <option key={a} value={a}>{a}</option>)}
              </select>
              <div className="min-w-0">
                {b.action === "click" && (
                  <select value={b.button} onChange={(e) => update(g, { button: e.target.value })} className={inputCls}>
                    <option value="left">left</option><option value="right">right</option><option value="middle">middle</option>
                  </select>)}
                {b.action === "scroll" && (
                  <input type="number" value={b.amount} onChange={(e) => update(g, { amount: parseInt(e.target.value) || 1 })} className={inputCls} placeholder="amount (+up / -down)" />)}
                {b.action === "hotkey" && (
                  <input value={b.keys} onChange={(e) => update(g, { keys: e.target.value })} className={inputCls} placeholder="e.g. ctrl+alt+t" />)}
                {b.action === "press" && (
                  <input value={b.key} onChange={(e) => update(g, { key: e.target.value })} className={inputCls} placeholder="e.g. enter, esc, f5" />)}
                {b.action === "type" && (
                  <input value={b.text} onChange={(e) => update(g, { text: e.target.value })} className={inputCls} placeholder="text to type" />)}
                {b.action === "media" && (
                  <select value={b.key} onChange={(e) => update(g, { key: e.target.value })} className={inputCls}>
                    {MEDIA.map((m) => <option key={m} value={m}>{m}</option>)}
                  </select>)}
                {b.action === "launch" && (
                  <input value={b.app} onChange={(e) => update(g, { app: e.target.value })} className={inputCls} placeholder="app (notepad / Safari / firefox)" />)}
                {b.action === "screenshot" && (
                  <input value={b.dir} onChange={(e) => update(g, { dir: e.target.value })} className={inputCls} placeholder="save folder e.g. ~/Pictures" />)}
                {b.action === "window" && (
                  <select value={b.op} onChange={(e) => update(g, { op: e.target.value })} className={inputCls}>
                    {WINDOW_OPS.map((o) => <option key={o} value={o}>{o}</option>)}
                  </select>)}
                {["none", "double_click", "drag", "pause_toggle"].includes(b.action) && (
                  <span className="text-[10px] text-zinc-600 font-mono">no parameters</span>)}
              </div>
              {CONTINUOUS.has(g) ? (
                <span className="text-[10px] text-zinc-600 font-mono text-center">instant</span>
              ) : (
                <label className="text-[10px] text-zinc-500 font-mono flex items-center justify-center gap-1 cursor-pointer" title="Fire only after holding ~1s">
                  <input type="checkbox" checked={b.hold !== false} onChange={(e) => update(g, { hold: e.target.checked })} data-testid={`config-hold-${g}`} className="accent-primary" /> hold
                </label>
              )}
            </div>
          );
        })}
      </div>
      <p className="text-[10px] text-zinc-600 font-mono">Tip: "hold" fires an action only after you hold the gesture ~1s (avoids accidents). Uncheck it for instant triggers. Continuous gestures (pinch / scroll) are always instant.</p>
    </div>
  );
}
